### ISSUE TITLE
Procedure for Dummies.

### ISSUE THREAD

**Issue by cassanelligiovanni** [evilarceus/Spotify-PlayCount#3]
I am trying to run the script from my terminal and I am stuck and cannot understand the following things  ( i probably don't understand them because of my lack of knowledge, so if you have articles, books, or  talks that can help me you are welcome )  

IP and SERVER
- Primarly,  port and the IP address have to be related to the WIFI I am connected to ? 
- Secondly, if I want to make it part of a bigger project. How would you interface a system in order to ask the playCount from a Front-END application to a server (you created one but i would like it to be private( since it would be more safe and reliable).

OPEN SPOTIFY.app
- "spotify --ignore-certificate-errors --allow-running-insecure-content" typing this from the terminal in my Application Folder gives me "command not found". 
How is it possible ? Do I type it in the right place ?

- ENDPOINTs
What endopoint should i put in the config.json ?
On [https://github.com/evilarceus/Spotify-PlayCount/issues/2] I saw that trjuntunen did : 
{ "endpoint": "/albums" } 
should I do like him ? 
-This one is linked to the first question : in an eutopic scenary how would you ask from the front-end the album play count ?

I know It is a lot of stuff and maybe it is not correct. but it will help a lot with approaching this script, which is by the way excellent and essential if you want to do any data analysis on the music out there

**Comment by entriphy** [comment]
- IP Address: If the server and the Spotify client are running on the same machine, leave this as 127.0.0.1 (known as the [loopback address](https://askubuntu.com/questions/247625/what-is-the-loopback-device-and-how-do-i-use-it)). This means that the Spotify client will connect to the server hosted on your own machine. If the Spotify client is running on a different machine than the server, then you'd use the IP address of the server.
- Port: This represents the port on which the HTTP sever runs on. The default is 8080 in the config. If you want to send a request to the server, you'd use the URL (assuming the IP address is 127.0.0.1 and endpoint is `/`) `http://127.0.0.1:8080?albumid=<album id>`. If you use port 80 (default port for HTTP connections), then you can use the URL `http://127.0.0.1?albumid=<album id>`
- Endpoint: You can leave this as `/`. This just says where to send requests to. If it's set to `/`, then the URL to send requests to is `http://127.0.0.1:8080?albumid=<album id>`. If it were `/albums`, then you'd send requests to `http://127.0.0.1:8080/albums?albumid=<album id>`
- Opening Spotify: I'm assuming you mean the `/Applications` folder on Mac. The correct directory is `/Applications/Spotify.app/Contents/MacOS/Spotify`. I believe you could just use the command `/Applications/Spotify.app/Contents/MacOS/Spotify --ignore-certificate-errors --allow-running-insecure-content` on Mac.
- Interfacing: Depends on what language you're using. If you haven't already, learn how to create an HTTP GET request to a URL and parse the JSON response using your language of choice (here's a tutorial for [JavaScript](https://www.freecodecamp.org/news/here-is-the-most-popular-ways-to-make-an-http-request-in-javascript-954ce8c95aaa/) and [Python](https://realpython.com/python-requests/)).

Hope I explained as much as possible. Don't forget to run `node spotify_zlink.js` whenever you change the config (the script automatically backs up your old `zlink.spa` file).

**Comment by cassanelligiovanni** [comment]
Thanks a lot everything is more clear now, but still I got stuck at step 4 :
From a new terminal window I run the command : 
`/Applications/Spotify.app/Contents/MacOS/Spotify --ignore-certificate-errors --allow-running-insecure-content`, and Spotify Start 👍 
Then : 
 Do I have to open a new terminal window and type `node index.js` ?
and then `get http://127.0.0.1:8080?albumid=11dh7pT3FRrGkI3TXl0e4k`?

Cause if I do it says   `listening on port 8080` but then nothin....

**Comment by trjuntunen** [comment]
I noticed this issue and wanted to add to this discussion since I was mentioned.

Even though I was able to get it to work in the past, for some reason I can't get it to work any more. I am getting a similar problem to cassanelligiovanni, where it says `listening on port 8080` but does not say `o_> quack (client connected)` as it did when it worked correctly last week. Sometimes it produces the error in the Spotify developer console something along the lines of `This needs to be over https <some 400 error>`. But most of the time no error is outputted into the console. I have tried redownloading Spotify and re-running the spotify_zlink.js file again and still can't get it to work again. When I make a request to the server it's still just the same `Spotify client could not be found` message.

**Comment by entriphy** [comment]
You have to start the server first (node index.js), start the Spotify client with the arguments, then open an album page on Spotify. (Yes, you will have to start 2 terminal sessions)

@trjuntunen You might need to use the launch arguments if you're getting an HTTPS error.

**Comment by cassanelligiovanni** [comment]
I did all you said: 
After replaced zlink.spa, I run the server `node index.js`,  I open spotify with the arguments and I click on a random album,
Then I search this on my browser : `http://127.0.0.1:8080/?albumid=11dh7pT3FRrGkI3TXl0e4k` and I get 

> {"success":false,"data":"Spotify client could not be found."}

What Am I doing wrong ?

**Comment by cassanelligiovanni** [comment]
This is the console from the spicitify  Dev Tools : 

[](https://ibb.co/C7sJsXX)

**Comment by cassanelligiovanni** [comment]
https://ibb.co/C7sJsXX

**Comment by entriphy** [comment]
Seems like it's not even attempting a connection to the server. Can you send me your zlink.spa file?

**Comment by cassanelligiovanni** [comment]
Here it is :
[zlink.spa.zip](https://github.com/evilarceus/Spotify-PlayCount/files/3701543/zlink.spa.zip)

**Comment by ericdvb** [comment]
@evilarceus running into the same issue. Running the app locally, but it never seems to make the ws connection to the Spotify client. Was there any resolution to this issue?

**Comment by entriphy** [comment]
(sorry for not following up quickly enough)

They updated a single letter in the `zlink.bundle.js` file in `zlink.spa`, which messed up the entire process lol. I committed some changes in the `spotify_zlink.js` script which should fix the issue some of you are having and prevent this from happening in the future. Pull the new changes and use your original `zlink.spa` file (should've automatically been backed up as `zlink_old_********.spa` in the project directory).

**Comment by ericdvb** [comment]
Not at all, thanks for making the changes so fast! I pulled the latest changes, made a new zlink.spa, fired the whole thing up, and definitely got further but still not able to get album json with playcounts. I started poking around a little bit on the express side. The Spotify client is successfully making the ws connection now, and I can see requests coming in from my front end with albumIds on them, but it looks like no messages are coming back from the Spotify client as the message event handler isn't firing at all.

My Spotify version as reported in the client is: 1.1.17.543.geb9254e9, is there other information that would be useful for investigating?

**Comment by entriphy** [comment]
They changed another letter in a different part of the code :P. Should be working fine now with the new changes.

**Comment by ottomundo** [comment]
Is it possible they changed another thing? because I'm suddenly not getting a connection from the spotify client, if so, whats the logic behind the code change

my version is 1.1.10

**Comment by entriphy** [comment]
> Is it possible they changed another thing? because I'm suddenly not getting a connection from the spotify client, if so, whats the logic behind the code change
> 
> my version is 1.1.10

That's an older version of Spotify, update to the latest (1.1.18). Make sure to go through the `zlink.spa` process again whenever Spotify updates.

**Comment by giovannicassanelli-cell** [comment]
Thanks a lot finally made it working !!!!

**Comment by giovannicassanelli-cell** [comment]
You can close the issue for me

**Comment by ShuaiW** [comment]
> * IP Address: If the server and the Spotify client are running on the same machine, leave this as 127.0.0.1 (known as the [loopback address](https://askubuntu.com/questions/247625/what-is-the-loopback-device-and-how-do-i-use-it)). This means that the Spotify client will connect to the server hosted on your own machine. If the Spotify client is running on a different machine than the server, then you'd use the IP address of the server.
> * Port: This represents the port on which the HTTP sever runs on. The default is 8080 in the config. If you want to send a request to the server, you'd use the URL (assuming the IP address is 127.0.0.1 and endpoint is `/`) `http://127.0.0.1:8080?albumid=<album id>`. If you use port 80 (default port for HTTP connections), then you can use the URL `http://127.0.0.1?albumid=<album id>`
> * Endpoint: You can leave this as `/`. This just says where to send requests to. If it's set to `/`, then the URL to send requests to is `http://127.0.0.1:8080?albumid=<album id>`. If it were `/albums`, then you'd send requests to `http://127.0.0.1:8080/albums?albumid=<album id>`
> * Opening Spotify: I'm assuming you mean the `/Applications` folder on Mac. The correct directory is `/Applications/Spotify.app/Contents/MacOS/Spotify`. I believe you could just use the command `/Applications/Spotify.app/Contents/MacOS/Spotify --ignore-certificate-errors --allow-running-insecure-content` on Mac.
> * Interfacing: Depends on what language you're using. If you haven't already, learn how to create an HTTP GET request to a URL and parse the JSON response using your language of choice (here's a tutorial for [JavaScript](https://www.freecodecamp.org/news/here-is-the-most-popular-ways-to-make-an-http-request-in-javascript-954ce8c95aaa/) and [Python](https://realpython.com/python-requests/)).
> 
> Hope I explained as much as possible. Don't forget to run `node spotify_zlink.js` whenever you change the config (the script automatically backs up your old `zlink.spa` file).

hey man thank you for making this! I followed the instruction and even get the `o_> quack (client connected)` response. But when I make a curl call it will stuck and then won't return the results. 
Using Spotify 1.1.24.91.g4ca6d5eb on Mac
